#cloud-config
users:
  - name: mikew
    ssh_import_id: gh:vicmike
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo, adm
    shell: /bin/bash
package_upgrade: true
packages:
  - htop
  - tmux
  - git
  - vim
  - curl
  - wget
  - unattended-upgrades
  - fail2ban
runcmd:
  - [ sh, -c, "rm -f /etc/ssh/ssh_host_*" ]
  - [ sh, -c, "dpkg-reconfigure openssh-server" ]
  - [ sh, -c, "dpkg-reconfigure -plow unattended-upgrades" ]
  - [ sysctl, -w, "net.ipv4.ip_forward=1" ]
  - [ sysctl, -w, "net.ipv6.conf.all.forwarding=1" ]
  - [ sysctl, -w, "net.bridge.bridge-nf-call-iptables=1" ]
  - [ sysctl, -w, "net.bridge.bridge-nf-call-ip6tables=1" ]
  - [ sysctl, -w, "vm.max_map_count=262144" ]
final_message: "The system is finally up, after $UPTIME seconds"
power_state:
  mode: reboot
